---
# module: rd-ansible-ntp/tasks/configure
# description: Configure rd-ansible-ntp

- name: Create a configuration for NTP in /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: "/etc/ntp.conf"
  notify:
    - force_update
    - restart_ntp
