---
# module: rd-ansible-ntp/tasks
# description: Install rd-ansible-ntp onto an Ubuntu 16 or 18 server, this will skip if its an lxc container

- include_tasks: install.yml
  when: ansible_virtualization_type|default('unknown') != 'lxc'
- include_tasks: configure.yml
  when: ansible_virtualization_type|default('unknown') != 'lxc'
